
service: lambda-emptor 
package:
  exclude:
    - node_modules/**
    - .git/**
    - __pycache__/**

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'dev'}
  region: us-east-2
  deploymentBucket: emptor-title
  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:*"
      Resource: "arn:aws:s3:::emptor-title/*"
  apiKeys: 
    - user-key-${opt:stage, 'dev'}
  
plugins:
  - serverless-python-requirements

functions:
  extracts_title:
    handler: handler.extracts_title
    events:
      - http:
          path: page/title
          method: post
