
service: lambda-emptor 

package:
  exclude:
    - node_modules/**
    - .git/**
    - __pycache__/**

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'dev'}
  region: us-east-2
  deploymentBucket: emptor-title
  environment:
    URL_TABLE: ${self:custom.urlTable}
    BUCKET: ${self:provider.deploymentBucket}
    SERVICE: ${self:service}
    STAGING: ${self:provider.stage}
  iamRoleStatements:
    - Effect: "Allow"
      Action: 
        - "s3:*"
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:ListStreams
      Resource: 
        - "arn:aws:s3:::emptor-title/*"
        - "Fn::GetAtt": [URLTable, Arn ]
        - "*"
  

  apiKeys: 
    - user-key-${opt:stage, 'dev'}


custom:
  urlTable: url-table-${self:provider.stage}

  
plugins:
  - serverless-python-requirements

functions:
  create_identifier:
    handler: handler.create_identifier
    events:
      - http:
          path: page/title
          method: post

  extracts_title:
    handler: handler.extracts_title
    events:
      - stream:
          type: dynamodb
          batchsize: 1
          startingPosition: LATEST
          arn:
            Fn::GetAtt:
              - URLTable
              - StreamArn

resources:
  # DynamoDB
  - ${file(resources/dynamodb-table.yml)}

